 * Starting OpenBSD Secure Shell server sshd
   ...done.
INFO:circe.py:Using base script preagg.py
DEBUG:circe.py:starting the input monitoring process
DEBUG:circe.py:starting the output monitoring process
7
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_2jobth6#93962419-6#90092041-6#87162309-6#48253157", "unix_time": 1620589348.8865745}
INFO:ccdag_utils.py:runtime_stat:{"task_name": "preagg7", "event": "queue_start_process", "filename": "score7b_preagg7_2jobth6#93962419-6#90092041-6#87162309-6#48253157", "unix_time": 1620589349.0784862}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_2jobth6#93962419-6#90092041-6#87162309-6#48253157", "unix_time": 1620589349.644681}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 144, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 153, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc76f4c1470>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.100.92.70', port=6100): Max retries exceeded with url: /post-dict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc76f4c1470>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/jupiter/build/app_specific_files/preagg.py", line 96, in task
    response =  requests.post(url, headers = hdr,data = json.dumps(payload))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.100.92.70', port=6100): Max retries exceeded with url: /post-dict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc76f4c1470>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/jupiter/build/app_specific_files/preagg.py", line 105, in task
    job_dict = {'2':[sample1[0],sample2[0]]}
IndexError: list index out of range

INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_2jobth6#93962419-6#90092041-6#87162309-6#48253157", "unix_time": 1620589357.6460335}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_2jobth6#35330881-6#59420124-6#76237806-6#87521250", "unix_time": 1620589379.2013483}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_2jobth6#35330881-6#59420124-6#76237806-6#87521250", "unix_time": 1620589379.297888}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_2jobth6#35330881-6#59420124-6#76237806-6#87521250", "unix_time": 1620589387.1683888}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_1jobth6#47438849-6#54151661-6#50571326-6#14565190", "unix_time": 1620589580.1648657}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_1jobth6#47438849-6#54151661-6#50571326-6#14565190", "unix_time": 1620589580.904355}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_1jobth6#47438849-6#54151661-6#50571326-6#14565190", "unix_time": 1620589588.9894264}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_2jobth6#63282646-6#34080153-6#18053285-6#17918478", "unix_time": 1620589688.6369724}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_2jobth6#63282646-6#34080153-6#18053285-6#17918478", "unix_time": 1620589690.442539}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_2jobth6#63282646-6#34080153-6#18053285-6#17918478", "unix_time": 1620589698.5722806}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_3jobth6#65836474-6#89276813-6#49365876-6#61840988", "unix_time": 1620589721.1829324}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_3jobth6#65836474-6#89276813-6#49365876-6#61840988", "unix_time": 1620589722.9630454}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_3jobth6#65836474-6#89276813-6#49365876-6#61840988", "unix_time": 1620589730.1487665}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_4jobth6#36199340-6#37377129-6#48504009-6#28369934", "unix_time": 1620589754.7373831}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_4jobth6#36199340-6#37377129-6#48504009-6#28369934", "unix_time": 1620589755.4968874}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_4jobth6#36199340-6#37377129-6#48504009-6#28369934", "unix_time": 1620589763.6927028}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_5jobth6#46129272-6#54113856-6#70622116-6#60612561", "unix_time": 1620589804.2594619}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_5jobth6#46129272-6#54113856-6#70622116-6#60612561", "unix_time": 1620589805.0454557}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_5jobth6#46129272-6#54113856-6#70622116-6#60612561", "unix_time": 1620589814.1615865}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_6jobth6#64814516-6#99628839-3#63731115-6#88158876", "unix_time": 1620589895.8607357}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_6jobth6#64814516-6#99628839-3#63731115-6#88158876", "unix_time": 1620589896.7363896}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_6jobth6#64814516-6#99628839-3#63731115-6#88158876", "unix_time": 1620589904.805171}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_7jobth6#90590259-6#81382316-6#48677429-6#44841699", "unix_time": 1620590085.496424}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_7jobth6#90590259-6#81382316-6#48677429-6#44841699", "unix_time": 1620590087.3531063}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_7jobth6#90590259-6#81382316-6#48677429-6#44841699", "unix_time": 1620590095.4524958}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7b_preagg7_8jobth6#31401503-6#06501118-6#18195562-6#58778575", "unix_time": 1620590313.2000566}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7c_preagg7_8jobth6#31401503-6#06501118-6#18195562-6#58778575", "unix_time": 1620590314.2500818}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score7a_preagg7_8jobth6#31401503-6#06501118-6#18195562-6#58778575", "unix_time": 1620590321.2302282}
